---

- name: Install jenkins dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ jenkins_dependencies }}"
  tags:
    - install
    - depend

- name: Configure docker daemon
  lineinfile:
    path: /etc/default/docker
    line: 'DOCKER_OPTS="-H unix:// -H tcp://localhost:2375"'
  notify: Restart docker

- name: Install pip dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - docker-py
    - jmespath
    - molecule
  tags:
    - install
    - depend

- name: Create Sonar server container
  docker_container:
    name: sonar
    image: sonarqube
    state: started
    recreate: no
    published_ports:
      - 9000:9000

- name: Update sudoers
  copy:
    src: jenkins
    dest: /etc/sudoers.d/jenkins
    owner: root
    group: root
    mode: 0600
  tags:
    - config
    - install
    - sudo

- name: "Install jenkins ver. {{ jenkins_ver}}"
  apt:
    deb: "{{ jenkins_url }}"
    state: present
  register: install_status
  tags:
    - install
    - apt

- name: Disable setup wizard.
  lineinfile:
    name: /etc/default/jenkins
    regexp: '^JAVA_ARGS="-Djava.*$'
    line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
  register: wizard_status
  tags:
    - install
    - wizard

- name: Add jenkins to docker group
  user:
    name: jenkins
    groups: docker
    append: yes
  tags:
    - docker

- name: Restart jenkins
  service:
    name: jenkins
    state: restarted
  when: wizard_status.changed or install_status.changed
  tags:
    - install

- name: Wait for Jenkins to start
  uri:
    url: http://localhost:8080/login
    status_code: 200
  register: result
  until: result.status == 200
  retries: 20
  delay: 40
  tags:
    - install

- name: Create default user admin and enable security
  uri:
    url: http://localhost:8080/scriptText
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    body: "script={{ lookup('file', jenkins_groovy_scripts_dir+ '/create_user_enble_security.groovy') | urlencode }}"
  tags:
    - security
    - credentials
    - groovy_script

- name: "Install plugin"
  uri:
    url: "http://localhost:8080/pluginManager/install?plugin.{{ item }}.default=on"
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    status_code:
      - 200
      - 302
  with_items: "{{ jenkins_plugins.plugins }}"
  changed_when: false
  tags:
    - plugin
    - install

- name: Wait for plugins to be installed
  uri:
    url: "http://localhost:8080/updateCenter/installStatus"
    return_content: yes
    body_format: json
    user: admin
    password: admin
    force_basic_auth: yes
  register: plugin_status
  until: "'Pending' not in plugin_status.json.data.jobs|map(attribute='installStatus')"
  retries: 100
  delay: 5
  tags:
    - plugins
    - install

- name: Restart jenkins
  service:
    name: jenkins
    state: restarted
  when: "'SuccessButRequiresRestart' in plugin_status.json.data.jobs|map(attribute='installStatus')"
  tags:
    - plugins
    - install

- name: Wait for Jenkins to start
  uri:
    url: http://localhost:8080/login
    status_code: 200
  register: result
  until: result.status == 200
  retries: 20
  delay: 40
  tags:
    - install
    - plugins

- name: Configure Jenkins
  uri:
    url: http://localhost:8080/scriptText
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    body: "script={{ lookup('file', jenkins_groovy_scripts_dir + '/jenkins_config_machine.groovy') | urlencode }}"
  tags:
    - config
    - groovy_script

- name: Ensure seed job folder exists
  file:
    path: /var/lib/jenkins/workspace/seed-job/jobs
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775
  tags:
    - install
    - config
    - seed_job

- name: Copy seed job to its workspace
  copy:
    src: create_all_jobs.groovy
    dest: /var/lib/jenkins/workspace/seed-job/jobs
    owner: jenkins
    group: jenkins
    mode: 0660
  tags:
    - install
    - config
    - seed_job

- name: Execute seed job
  uri:
    url: http://localhost:8080/job/seed-job/build?token=TOKENVANDHRV73hbc5dsj
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    status_code: 201
  tags:
    - seed_job
    - config
