---

jenkins_ver: 2.89.3
jenkins_url: https://pkg.jenkins.io/debian-stable/binary/jenkins_{{ jenkins_ver }}_all.deb
jenkins_disable_wizard: True
jenkins_groovy_scripts_dir: /vagrant/provisioning/groovy
jenkins_dependencies:
  - mc
  - openjdk-8-jdk
  - daemon
  - wget
  - jq
jenkins_plugins:
  dynamicLoad: true
  plugins:
    - cloudbees-folder
    - antisamy-markup-formatter
    - build-timeout
    - credentials-binding
    - timestamper
    - ws-cleanup
    - workflow-aggregator
    - github-organization-folder
    - git
    - subversion
    - ssh-slaves
    - matrix-auth
    - pam-auth
    - ldap
    - email-ext
    - mailer
    - custom-tools-plugin
    - htmlpublisher
    - zap
    - authorize-project
    - workflow-aggregator
    - ansicolor
