# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

cluster = [{:hostname => "server", :cpu => "1", :mem => "1024", :box => "ubuntu/xenial64", :prov_script => "provisioning/server.sh", :ip => "192.168.1.165"},
           {:hostname => "node1", :cpu => "1", :mem => "1024", :box => "ubuntu/xenial64", :prov_script => "provisioning/node.sh", :ip => "192.168.1.166"},
           {:hostname => "node2", :cpu => "1", :mem => "1024", :box => "ubuntu/xenial64", :prov_script => "provisioning/node.sh", :ip => "192.168.1.167"}
          ]

#cluster = [{:hostname => "master", :cpu => "2", :mem => "3328", :box => "ubuntu/xenial64", :prov_script => "provisioning/server.sh", :ip => "192.168.1.165"}]

Vagrant.configure(2) do |config|
  cluster.each do |inst|
    config.vm.define inst[:hostname] do |node|
      node.vm.box = inst[:box]
      node.vm.hostname = inst[:hostname]
      node.vm.network "public_network", bridge: "wlp8s0", ip: inst[:ip]
      node.vm.provider "virtualbox" do |cfg|
        cfg.customize ["modifyvm", :id, "--memory", inst[:mem]]
        cfg.customize ["modifyvm", :id, "--cpus", inst[:cpu]]
      end
      node.vm.provision :shell, :path => inst[:prov_script]
      end
  end

end
